In [1]:
import pandas as pd

In [11]:
a = pd.Series(range(10,51,10))
a

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
data = ['Chitwan','Kathmandu','Pokhara']
label = [10,15,9]
da = pd.Series(data,index=label)
da

10      Chitwan
15    Kathmandu
9       Pokhara
dtype: str

In [12]:
a.max()

np.int64(50)

In [13]:
a.min()

np.int64(10)

In [14]:
a.mean()

np.float64(30.0)

In [15]:
a.sum()

np.int64(150)

In [19]:
marks = [85,90,78,88]
sub = ['Math','Science','English','Nepali']
grade = pd.Series(sub,index=marks)

In [41]:
df = pd.DataFrame({
    'Subject':sub,
    'Marks':marks
})

In [42]:
df[df['Subject'].isin(['Math','English'])]

   Subject  Marks
0     Math     85
2  English     78

In [43]:
df['Marks']+5

0    90
1    95
2    83
3    93
Name: Marks, dtype: int64

In [44]:
df['Marks']*2

0    170
1    180
2    156
3    176
Name: Marks, dtype: int64

In [46]:
lsi=["Apple","Banana","Orange","Mango","Grapes"]
lis_series = pd.Series(lsi)
lis_series

0     Apple
1    Banana
2    Orange
3     Mango
4    Grapes
dtype: str

In [47]:
dic ={
    "Nepal":300,
    "India":1400,
    "China":1450
}
pd.Series(dic)

Nepal     300
India    1400
China    1450
dtype: int64

In [ ]:
| Name    | Age | City      |
| ------- | --- | --------- |
| Alice   | 25  | Kathmandu |
| Bob     | 30  | Pokhara   |
| Charlie | 28  | Lalitpur  |
| David   | 35  | Butwal    |

In [49]:
name =['Alice','Bob','Charlie','David']
Age =[25,30,28,35]
City =['Kathmandu','Pokhara','Lalitpur','Chitwan']

dataf = pd.DataFrame(
    {
        'Name':name,
        'Age':Age,
        'City':City
    }
)
dataf

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur
3    David   35    Chitwan

In [50]:
dataf.head(2)

    Name  Age       City
0  Alice   25  Kathmandu
1    Bob   30    Pokhara

In [51]:
dataf.tail(2)

      Name  Age      City
2  Charlie   28  Lalitpur
3    David   35   Chitwan

In [53]:
dataf.shape

(4, 3)

In [54]:
dataf.size

12

In [55]:
dataf.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [56]:
dataf.index

RangeIndex(start=0, stop=4, step=1)

In [59]:
type(dataf)

pandas.DataFrame

In [63]:
dataf.dtypes

Name      str
Age     int64
City      str
dtype: object

In [64]:
dataf

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur
3    David   35    Chitwan

In [66]:
dataf['Name']

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [72]:
dataf.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [75]:
dataf[['Name','Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   28
3    David   35

In [84]:
dataf.loc[0:0,::]

    Name  Age       City
0  Alice   25  Kathmandu

In [87]:
dataf.iloc[1:2,::]

  Name  Age     City
1  Bob   30  Pokhara

In [88]:
salary=[50000,
60000,
55000,
70000]
dataf

      Name  Age       City
0    Alice   25  Kathmandu
1      Bob   30    Pokhara
2  Charlie   28   Lalitpur
3    David   35    Chitwan

In [90]:
dataf['Salary']=salary
dataf

      Name  Age       City  Salary
0    Alice   25  Kathmandu   50000
1      Bob   30    Pokhara   60000
2  Charlie   28   Lalitpur   55000
3    David   35    Chitwan   70000

In [91]:
dataf['Salary']

0    50000
1    60000
2    55000
3    70000
Name: Salary, dtype: int64

In [125]:
dataf['Bonus']=dataf['Salary']*0.1
dataf

      Name  Age       City  Salary  TotalSalary   Bonus
0    Alice   25  Kathmandu   50000      55000.0  5000.0
1      Bob   30    Pokhara   60000      66000.0  6000.0
2  Charlie   28   Lalitpur   55000      60500.0  5500.0
3    David   35    Chitwan   70000      77000.0  7000.0

In [126]:
dataf['TotalSalary']=dataf['Salary']+dataf['Bonus']
dataf

      Name  Age       City  Salary  TotalSalary   Bonus
0    Alice   25  Kathmandu   50000      55000.0  5000.0
1      Bob   30    Pokhara   60000      66000.0  6000.0
2  Charlie   28   Lalitpur   55000      60500.0  5500.0
3    David   35    Chitwan   70000      77000.0  7000.0

In [127]:
dataf.drop('Bonus',axis=1,inplace=True) # dleete Bonus

In [128]:
dataf

      Name  Age       City  Salary  TotalSalary
0    Alice   25  Kathmandu   50000      55000.0
1      Bob   30    Pokhara   60000      66000.0
2  Charlie   28   Lalitpur   55000      60500.0
3    David   35    Chitwan   70000      77000.0

In [131]:
dataf['Address']=dataf['City']
dataf

      Name  Age       City  Salary  TotalSalary    Address
0    Alice   25  Kathmandu   50000      55000.0  Kathmandu
1      Bob   30    Pokhara   60000      66000.0    Pokhara
2  Charlie   28   Lalitpur   55000      60500.0   Lalitpur
3    David   35    Chitwan   70000      77000.0    Chitwan

In [132]:
dataf.drop('City',axis=1,inplace=True)

In [133]:
dataf

      Name  Age  Salary  TotalSalary    Address
0    Alice   25   50000      55000.0  Kathmandu
1      Bob   30   60000      66000.0    Pokhara
2  Charlie   28   55000      60500.0   Lalitpur
3    David   35   70000      77000.0    Chitwan

In [134]:
read = pd.read_csv(r"/Users/rohitshrestha/Projects/datascience_codeit/Pandas_Practice_Dataset.csv")
read

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [135]:
read.head()

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar

In [136]:
read.tail()

   EmpID   Name Department  Age  Salary  Experience       City
5    106  Frank      Sales   40   90000          15     Butwal
6    107  Grace         IT   24   48000           1     Dharan
7    108  Helen    Finance   33   70000           8    Chitwan
8    109    Ian         HR   28   52000           3  Nepalgunj
9    110   Jane  Marketing   30   61000           5   Janakpur

In [137]:
read_json = pd.read_json(r"/Users/rohitshrestha/Projects/datascience_codeit/Pandas_Practice_Dataset.json")
read_json

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [138]:
read_json.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       10 non-null     int64
 1   Name        10 non-null     str
 2   Department  10 non-null     str
 3   Age         10 non-null     int64
 4   Salary      10 non-null     int64
 5   Experience  10 non-null     int64
 6   City        10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

In [139]:
read_excel = pd.read_excel(r"/Users/rohitshrestha/Projects/datascience_codeit/Pandas_Practice_Dataset.xlsx")
read_excel

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [141]:
read_excel[['Department','Salary']]

  Department  Salary
0         IT   50000
1         HR   62000
2    Finance   58000
3         IT   80000
4  Marketing   54000
5      Sales   90000
6         IT   48000
7    Finance   70000
8         HR   52000
9  Marketing   61000

In [142]:
read_excel[read_excel['Age']>30]

   EmpID   Name Department  Age  Salary  Experience       City
1    102    Bob         HR   31   62000           6    Pokhara
3    104  David         IT   35   80000          10  Bhaktapur
5    106  Frank      Sales   40   90000          15     Butwal
7    108  Helen    Finance   33   70000           8    Chitwan

In [147]:
read[read['Salary']>60000]

   EmpID   Name Department  Age  Salary  Experience       City
1    102    Bob         HR   31   62000           6    Pokhara
3    104  David         IT   35   80000          10  Bhaktapur
5    106  Frank      Sales   40   90000          15     Butwal
7    108  Helen    Finance   33   70000           8    Chitwan
9    110   Jane  Marketing   30   61000           5   Janakpur

In [146]:
read[read['Department'].isin(['IT'])]

   EmpID   Name Department  Age  Salary  Experience       City
0    101  Alice         IT   25   50000           2  Kathmandu
3    104  David         IT   35   80000          10  Bhaktapur
6    107  Grace         IT   24   48000           1     Dharan

In [158]:
read

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [157]:
read['Salary'].min()

np.int64(48000)

In [159]:
read['Salary'].max()

np.int64(90000)

In [160]:
read['Salary'].mean()

np.float64(62500.0)

In [161]:
read['Department'].value_counts() # count the value of department

Department
IT           3
HR           2
Finance      2
Marketing    2
Sales        1
Name: count, dtype: int64

In [165]:
read['Salary'].sort_values()

6    48000
0    50000
8    52000
4    54000
2    58000
9    61000
1    62000
7    70000
3    80000
5    90000
Name: Salary, dtype: int64

In [167]:
read.sort_values(by='Salary', ascending=False)

   EmpID     Name Department  Age  Salary  Experience        City
5    106    Frank      Sales   40   90000          15      Butwal
3    104    David         IT   35   80000          10   Bhaktapur
7    108    Helen    Finance   33   70000           8     Chitwan
1    102      Bob         HR   31   62000           6     Pokhara
9    110     Jane  Marketing   30   61000           5    Janakpur
2    103  Charlie    Finance   29   58000           4    Lalitpur
4    105      Eva  Marketing   27   54000           3  Biratnagar
8    109      Ian         HR   28   52000           3   Nepalgunj
0    101    Alice         IT   25   50000           2   Kathmandu
6    107    Grace         IT   24   48000           1      Dharan

In [169]:
con1 = read['Age']>25
con2 = read['Age']<35
read[con1 & con2]

   EmpID     Name Department  Age  Salary  Experience        City
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
4    105      Eva  Marketing   27   54000           3  Biratnagar
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [187]:
con3 = read[read['Department'].isin(['IT'])]
con3

   EmpID   Name Department  Age  Salary  Experience       City
0    101  Alice         IT   25   50000           2  Kathmandu
3    104  David         IT   35   80000          10  Bhaktapur
6    107  Grace         IT   24   48000           1     Dharan

In [188]:
con3[['Name','City']]

    Name       City
0  Alice  Kathmandu
3  David  Bhaktapur
6  Grace     Dharan

In [190]:
read[read['Salary']==read['Salary'].max()]

   EmpID   Name Department  Age  Salary  Experience    City
5    106  Frank      Sales   40   90000          15  Butwal

In [193]:
read['Tax']=read['Salary']*0.05
read

   EmpID     Name Department  Age  Salary  Experience        City     Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500.0
1    102      Bob         HR   31   62000           6     Pokhara  3100.0
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900.0
3    104    David         IT   35   80000          10   Bhaktapur  4000.0
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700.0
5    106    Frank      Sales   40   90000          15      Butwal  4500.0
6    107    Grace         IT   24   48000           1      Dharan  2400.0
7    108    Helen    Finance   33   70000           8     Chitwan  3500.0
8    109      Ian         HR   28   52000           3   Nepalgunj  2600.0
9    110     Jane  Marketing   30   61000           5    Janakpur  3050.0

new_employee.csv
new_employee.xlsx
new_employee.json

In [196]:
read.to_csv('new_employee.csv', index=False)

In [199]:
read.to_json('new_employee.json', index=False)

In [202]:
read.to_excel('new_employee.xlsx', index=False)

read.to_json(
    "new_employee.json",
    orient="records",
    indent=4
)

In [149]:
xyz =read_excel.describe()

In [150]:
xyz

           EmpID        Age        Salary  Experience
count   10.00000  10.000000     10.000000   10.000000
mean   105.50000  30.200000  62500.000000    5.700000
std      3.02765   4.825856  13705.230145    4.270051
min    101.00000  24.000000  48000.000000    1.000000
25%    103.25000  27.250000  52500.000000    3.000000
50%    105.50000  29.500000  59500.000000    4.500000
75%    107.75000  32.500000  68000.000000    7.500000
max    110.00000  40.000000  90000.000000   15.000000