In [1]:
import pandas as pd

Data cleaning with pandas
reanaming adding droping columns

In [2]:
data = pd.read_excel(r'new_employee.xlsx')
data

   EmpID     Name Department  Age  Salary  Experience        City   Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500
1    102      Bob         HR   31   62000           6     Pokhara  3100
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900
3    104    David         IT   35   80000          10   Bhaktapur  4000
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700
5    106    Frank      Sales   40   90000          15      Butwal  4500
6    107    Grace         IT   24   48000           1      Dharan  2400
7    108    Helen    Finance   33   70000           8     Chitwan  3500
8    109      Ian         HR   28   52000           3   Nepalgunj  2600
9    110     Jane  Marketing   30   61000           5    Janakpur  3050

In [6]:
data.rename(columns={'EmpID':'ID'})

    ID     Name Department  Age  Salary  Experience        City   Tax
0  101    Alice         IT   25   50000           2   Kathmandu  2500
1  102      Bob         HR   31   62000           6     Pokhara  3100
2  103  Charlie    Finance   29   58000           4    Lalitpur  2900
3  104    David         IT   35   80000          10   Bhaktapur  4000
4  105      Eva  Marketing   27   54000           3  Biratnagar  2700
5  106    Frank      Sales   40   90000          15      Butwal  4500
6  107    Grace         IT   24   48000           1      Dharan  2400
7  108    Helen    Finance   33   70000           8     Chitwan  3500
8  109      Ian         HR   28   52000           3   Nepalgunj  2600
9  110     Jane  Marketing   30   61000           5    Janakpur  3050

In [7]:
data

   EmpID     Name Department  Age  Salary  Experience        City   Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500
1    102      Bob         HR   31   62000           6     Pokhara  3100
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900
3    104    David         IT   35   80000          10   Bhaktapur  4000
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700
5    106    Frank      Sales   40   90000          15      Butwal  4500
6    107    Grace         IT   24   48000           1      Dharan  2400
7    108    Helen    Finance   33   70000           8     Chitwan  3500
8    109      Ian         HR   28   52000           3   Nepalgunj  2600
9    110     Jane  Marketing   30   61000           5    Janakpur  3050

In [8]:
data.rename(columns={'EmpID':'ID'},inplace=True) # inplace will save the cahnges in the file

In [9]:
data

    ID     Name Department  Age  Salary  Experience        City   Tax
0  101    Alice         IT   25   50000           2   Kathmandu  2500
1  102      Bob         HR   31   62000           6     Pokhara  3100
2  103  Charlie    Finance   29   58000           4    Lalitpur  2900
3  104    David         IT   35   80000          10   Bhaktapur  4000
4  105      Eva  Marketing   27   54000           3  Biratnagar  2700
5  106    Frank      Sales   40   90000          15      Butwal  4500
6  107    Grace         IT   24   48000           1      Dharan  2400
7  108    Helen    Finance   33   70000           8     Chitwan  3500
8  109      Ian         HR   28   52000           3   Nepalgunj  2600
9  110     Jane  Marketing   30   61000           5    Janakpur  3050

In [16]:
data.drop(columns='Tax',inplace=True)

In [17]:
data

    ID     Name Department  Age  Salary  Experience        City
0  101    Alice         IT   25   50000           2   Kathmandu
1  102      Bob         HR   31   62000           6     Pokhara
2  103  Charlie    Finance   29   58000           4    Lalitpur
3  104    David         IT   35   80000          10   Bhaktapur
4  105      Eva  Marketing   27   54000           3  Biratnagar
5  106    Frank      Sales   40   90000          15      Butwal
6  107    Grace         IT   24   48000           1      Dharan
7  108    Helen    Finance   33   70000           8     Chitwan
8  109      Ian         HR   28   52000           3   Nepalgunj
9  110     Jane  Marketing   30   61000           5    Janakpur

In [18]:
data.drop('Name',axis=1)

    ID Department  Age  Salary  Experience        City
0  101         IT   25   50000           2   Kathmandu
1  102         HR   31   62000           6     Pokhara
2  103    Finance   29   58000           4    Lalitpur
3  104         IT   35   80000          10   Bhaktapur
4  105  Marketing   27   54000           3  Biratnagar
5  106      Sales   40   90000          15      Butwal
6  107         IT   24   48000           1      Dharan
7  108    Finance   33   70000           8     Chitwan
8  109         HR   28   52000           3   Nepalgunj
9  110  Marketing   30   61000           5    Janakpur

In [22]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Department  10 non-null     str
 3   Age         10 non-null     int64
 4   Salary      10 non-null     int64
 5   Experience  10 non-null     int64
 6   City        10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

In [25]:
data.select_dtypes('int64')

    ID  Age  Salary  Experience
0  101   25   50000           2
1  102   31   62000           6
2  103   29   58000           4
3  104   35   80000          10
4  105   27   54000           3
5  106   40   90000          15
6  107   24   48000           1
7  108   33   70000           8
8  109   28   52000           3
9  110   30   61000           5

In [26]:
data

    ID     Name Department  Age  Salary  Experience        City
0  101    Alice         IT   25   50000           2   Kathmandu
1  102      Bob         HR   31   62000           6     Pokhara
2  103  Charlie    Finance   29   58000           4    Lalitpur
3  104    David         IT   35   80000          10   Bhaktapur
4  105      Eva  Marketing   27   54000           3  Biratnagar
5  106    Frank      Sales   40   90000          15      Butwal
6  107    Grace         IT   24   48000           1      Dharan
7  108    Helen    Finance   33   70000           8     Chitwan
8  109      Ian         HR   28   52000           3   Nepalgunj
9  110     Jane  Marketing   30   61000           5    Janakpur

In [27]:
data['Tax']=data['Salary']*0.13

In [28]:
data

    ID     Name Department  Age  Salary  Experience        City      Tax
0  101    Alice         IT   25   50000           2   Kathmandu   6500.0
1  102      Bob         HR   31   62000           6     Pokhara   8060.0
2  103  Charlie    Finance   29   58000           4    Lalitpur   7540.0
3  104    David         IT   35   80000          10   Bhaktapur  10400.0
4  105      Eva  Marketing   27   54000           3  Biratnagar   7020.0
5  106    Frank      Sales   40   90000          15      Butwal  11700.0
6  107    Grace         IT   24   48000           1      Dharan   6240.0
7  108    Helen    Finance   33   70000           8     Chitwan   9100.0
8  109      Ian         HR   28   52000           3   Nepalgunj   6760.0
9  110     Jane  Marketing   30   61000           5    Janakpur   7930.0

handling missing value with fillna and dropna

In [29]:
# isna() used to find null or missing value

SyntaxError: invalid syntax (1022707672.py, line 1)

In [31]:
data.isna().sum()

ID            0
Name          0
Department    0
Age           0
Salary        0
Experience    0
City          0
Tax           0
dtype: int64

In [33]:
data

    ID     Name Department  Age  Salary  Experience        City      Tax
0  101    Alice         IT   25   50000           2   Kathmandu   6500.0
1  102      Bob         HR   31   62000           6     Pokhara   8060.0
2  103  Charlie    Finance   29   58000           4    Lalitpur   7540.0
3  104    David         IT   35   80000          10   Bhaktapur  10400.0
4  105      Eva  Marketing   27   54000           3  Biratnagar   7020.0
5  106    Frank      Sales   40   90000          15      Butwal  11700.0
6  107    Grace         IT   24   48000           1      Dharan   6240.0
7  108    Helen    Finance   33   70000           8     Chitwan   9100.0
8  109      Ian         HR   28   52000           3   Nepalgunj   6760.0
9  110     Jane  Marketing   30   61000           5    Janakpur   7930.0

In [42]:
data['test'] = [1,None,3,None,5,6,7,None,9,10]

In [43]:
data.isnull().sum()

ID             0
Name           0
Department     0
Age            0
Salary         0
Experience     0
City           0
Tax            0
null_val      10
test           3
dtype: int64

In [46]:
data.drop('null_val',axis=1,inplace=True)

In [47]:
data

    ID     Name Department  Age  Salary  Experience        City      Tax  test
0  101    Alice         IT   25   50000           2   Kathmandu   6500.0   1.0
1  102      Bob         HR   31   62000           6     Pokhara   8060.0   NaN
2  103  Charlie    Finance   29   58000           4    Lalitpur   7540.0   3.0
3  104    David         IT   35   80000          10   Bhaktapur  10400.0   NaN
4  105      Eva  Marketing   27   54000           3  Biratnagar   7020.0   5.0
5  106    Frank      Sales   40   90000          15      Butwal  11700.0   6.0
6  107    Grace         IT   24   48000           1      Dharan   6240.0   7.0
7  108    Helen    Finance   33   70000           8     Chitwan   9100.0   NaN
8  109      Ian         HR   28   52000           3   Nepalgunj   6760.0   9.0
9  110     Jane  Marketing   30   61000           5    Janakpur   7930.0  10.0

In [48]:
data.dropna()

    ID     Name Department  Age  Salary  Experience        City      Tax  test
0  101    Alice         IT   25   50000           2   Kathmandu   6500.0   1.0
2  103  Charlie    Finance   29   58000           4    Lalitpur   7540.0   3.0
4  105      Eva  Marketing   27   54000           3  Biratnagar   7020.0   5.0
5  106    Frank      Sales   40   90000          15      Butwal  11700.0   6.0
6  107    Grace         IT   24   48000           1      Dharan   6240.0   7.0
8  109      Ian         HR   28   52000           3   Nepalgunj   6760.0   9.0
9  110     Jane  Marketing   30   61000           5    Janakpur   7930.0  10.0

In [49]:
data

    ID     Name Department  Age  Salary  Experience        City      Tax  test
0  101    Alice         IT   25   50000           2   Kathmandu   6500.0   1.0
1  102      Bob         HR   31   62000           6     Pokhara   8060.0   NaN
2  103  Charlie    Finance   29   58000           4    Lalitpur   7540.0   3.0
3  104    David         IT   35   80000          10   Bhaktapur  10400.0   NaN
4  105      Eva  Marketing   27   54000           3  Biratnagar   7020.0   5.0
5  106    Frank      Sales   40   90000          15      Butwal  11700.0   6.0
6  107    Grace         IT   24   48000           1      Dharan   6240.0   7.0
7  108    Helen    Finance   33   70000           8     Chitwan   9100.0   NaN
8  109      Ian         HR   28   52000           3   Nepalgunj   6760.0   9.0
9  110     Jane  Marketing   30   61000           5    Janakpur   7930.0  10.0

In [50]:
data.isna().sum()

ID            0
Name          0
Department    0
Age           0
Salary        0
Experience    0
City          0
Tax           0
test          3
dtype: int64

In [52]:
mean_avl = data.test.mean()

In [57]:
data['test']=data.test.fillna(mean_avl)

In [58]:
data

,ID,Name,Department,Age,Salary,Experience,City,Tax,test
0,101,Alice,IT,25,50000,2,Kathmandu,6500.0,1.000000
1,102,Bob,HR,31,62000,6,Pokhara,8060.0,5.857143
2,103,Charlie,Finance,29,58000,4,Lalitpur,7540.0,3.000000
3,104,David,IT,35,80000,10,Bhaktapur,10400.0,5.857143
4,105,Eva,Marketing,27,54000,3,Biratnagar,7020.0,5.000000
5,106,Frank,Sales,40,90000,15,Butwal,11700.0,6.000000
6,107,Grace,IT,24,48000,1,Dharan,6240.0,7.000000
7,108,Helen,Finance,33,70000,8,Chitwan,9100.0,5.857143
8,109,Ian,HR,28,52000,3,Nepalgunj,6760.0,9.000000
9,110,Jane,Marketing,30,61000,5,Janakpur,7930.0,10.000000