In [1]:
import pandas as pd

In [ ]:
# if missing data is more than 5% then reject the data

In [2]:
data = pd.read_json(r'new_employee.json')
data

   EmpID     Name Department  Age  Salary  Experience        City   Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500
1    102      Bob         HR   31   62000           6     Pokhara  3100
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900
3    104    David         IT   35   80000          10   Bhaktapur  4000
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700
5    106    Frank      Sales   40   90000          15      Butwal  4500
6    107    Grace         IT   24   48000           1      Dharan  2400
7    108    Helen    Finance   33   70000           8     Chitwan  3500
8    109      Ian         HR   28   52000           3   Nepalgunj  2600
9    110     Jane  Marketing   30   61000           5    Janakpur  3050

In [17]:
data

   EmpID     Name Department  Age  Salary  Experience        City   Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500
1    102      Bob         HR   31   62000           6     Pokhara  3100
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900
3    104    David         IT   35   80000          10   Bhaktapur  4000
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700
5    106    Frank      Sales   40   90000          15      Butwal  4500
6    107    Grace         IT   24   48000           1      Dharan  2400
7    108    Helen    Finance   33   70000           8     Chitwan  3500
8    109      Ian         HR   28   52000           3   Nepalgunj  2600
9    110     Jane  Marketing   30   61000           5    Janakpur  3050

In [18]:
df = data
df

   EmpID     Name Department  Age  Salary  Experience        City   Tax
0    101    Alice         IT   25   50000           2   Kathmandu  2500
1    102      Bob         HR   31   62000           6     Pokhara  3100
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900
3    104    David         IT   35   80000          10   Bhaktapur  4000
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700
5    106    Frank      Sales   40   90000          15      Butwal  4500
6    107    Grace         IT   24   48000           1      Dharan  2400
7    108    Helen    Finance   33   70000           8     Chitwan  3500
8    109      Ian         HR   28   52000           3   Nepalgunj  2600
9    110     Jane  Marketing   30   61000           5    Janakpur  3050

In [19]:
df['test']=[None,12,313,544,233,345,435,None,None,None]

In [20]:
df.isna().sum()

EmpID         0
Name          0
Department    0
Age           0
Salary        0
Experience    0
City          0
Tax           0
test          4
dtype: int64

In [21]:
df.shape

(10, 9)

In [7]:
4/10

0.4

In [22]:
df

   EmpID     Name Department  Age  Salary  Experience        City   Tax   test
0    101    Alice         IT   25   50000           2   Kathmandu  2500    NaN
1    102      Bob         HR   31   62000           6     Pokhara  3100   12.0
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900  313.0
3    104    David         IT   35   80000          10   Bhaktapur  4000  544.0
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700  233.0
5    106    Frank      Sales   40   90000          15      Butwal  4500  345.0
6    107    Grace         IT   24   48000           1      Dharan  2400  435.0
7    108    Helen    Finance   33   70000           8     Chitwan  3500    NaN
8    109      Ian         HR   28   52000           3   Nepalgunj  2600    NaN
9    110     Jane  Marketing   30   61000           5    Janakpur  3050    NaN

In [29]:
df['test']=df['test'].bfill() # fill na with backward value
df

   EmpID     Name Department  Age  Salary  Experience        City   Tax   test
0    101    Alice         IT   25   50000           2   Kathmandu  2500   12.0
1    102      Bob         HR   31   62000           6     Pokhara  3100   12.0
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900  313.0
3    104    David         IT   35   80000          10   Bhaktapur  4000  544.0
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700  233.0
5    106    Frank      Sales   40   90000          15      Butwal  4500  345.0
6    107    Grace         IT   24   48000           1      Dharan  2400  435.0
7    108    Helen    Finance   33   70000           8     Chitwan  3500  435.0
8    109      Ian         HR   28   52000           3   Nepalgunj  2600  435.0
9    110     Jane  Marketing   30   61000           5    Janakpur  3050  435.0

In [27]:
df['test']=df['test'].ffill() # fill na with forward value

In [28]:
df

   EmpID     Name Department  Age  Salary  Experience        City   Tax   test
0    101    Alice         IT   25   50000           2   Kathmandu  2500   12.0
1    102      Bob         HR   31   62000           6     Pokhara  3100   12.0
2    103  Charlie    Finance   29   58000           4    Lalitpur  2900  313.0
3    104    David         IT   35   80000          10   Bhaktapur  4000  544.0
4    105      Eva  Marketing   27   54000           3  Biratnagar  2700  233.0
5    106    Frank      Sales   40   90000          15      Butwal  4500  345.0
6    107    Grace         IT   24   48000           1      Dharan  2400  435.0
7    108    Helen    Finance   33   70000           8     Chitwan  3500  435.0
8    109      Ian         HR   28   52000           3   Nepalgunj  2600  435.0
9    110     Jane  Marketing   30   61000           5    Janakpur  3050  435.0

aggregation and merging

In [30]:
# groupby  - arranging data which have similarity

In [38]:
grp_dep =data.groupby('Department')
grp_dep

In [40]:
grp_dep['Salary'].mean() # mean by groupby department

Department
Finance      64000.000000
HR           57000.000000
IT           59333.333333
Marketing    57500.000000
Sales        90000.000000
Name: Salary, dtype: float64

In [42]:
data['Salary'].mean()

np.float64(62500.0)

In [43]:
grp_dep['Salary'].mean().sort_values(ascending=True)

Department
HR           57000.000000
Marketing    57500.000000
IT           59333.333333
Finance      64000.000000
Sales        90000.000000
Name: Salary, dtype: float64

In [44]:
grp_dep['Salary'].mean().sort_values(ascending=False)

Department
Sales        90000.000000
Finance      64000.000000
IT           59333.333333
Marketing    57500.000000
HR           57000.000000
Name: Salary, dtype: float64

In [45]:
data.groupby(['Salary','Department'])['Salary'].mean()

Salary  Department
48000   IT            48000.0
50000   IT            50000.0
52000   HR            52000.0
54000   Marketing     54000.0
58000   Finance       58000.0
61000   Marketing     61000.0
62000   HR            62000.0
70000   Finance       70000.0
80000   IT            80000.0
90000   Sales         90000.0
Name: Salary, dtype: float64