In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'Pandas_Practice_Dataset.csv')

In [3]:
data

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

 Explore 
 - columns
 - unique
 - nunique
 - valuecount
 - max
 - min
 - mean
 - median
 - mode
 - std
 - quantile
 - sort
 - sortby

In [5]:
data.columns

Index(['EmpID', 'Name', 'Department', 'Age', 'Salary', 'Experience', 'City'], dtype='str')

In [6]:
data.info

<bound method DataFrame.info of    EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur>

In [9]:
data['Department'].unique()

<StringArray>
['IT', 'HR', 'Finance', 'Marketing', 'Sales']
Length: 5, dtype: str

In [10]:
data.Department.unique()

<StringArray>
['IT', 'HR', 'Finance', 'Marketing', 'Sales']
Length: 5, dtype: str

In [12]:
data.Department.nunique()

5

In [14]:
data.Department.value_counts()

Department
IT           3
HR           2
Finance      2
Marketing    2
Sales        1
Name: count, dtype: int64

In [15]:
data.Salary.max()

np.int64(90000)

In [16]:
data.Salary.min()

np.int64(48000)

In [17]:
data.Salary.mean()

np.float64(62500.0)

In [21]:
data.Department.mode()

0    IT
Name: Department, dtype: str

In [19]:
data.Salary.median()

np.float64(59500.0)

In [52]:
data[['Salary','Age']].agg(['min','max','mean'])

       Salary   Age
min   48000.0  24.0
max   90000.0  40.0
mean  62500.0  30.2

In [20]:
data.Salary.std()

np.float64(13705.230145215854)

In [24]:
data.Salary.quantile(0.25)

np.float64(52500.0)

In [25]:
data.Salary.quantile(0.50)

np.float64(59500.0)

In [26]:
data.Salary.quantile(0.750)

np.float64(68000.0)

In [27]:
data.Salary.quantile(1)

np.float64(90000.0)

In [32]:
data.sort_values(by='Salary')

   EmpID     Name Department  Age  Salary  Experience        City
6    107    Grace         IT   24   48000           1      Dharan
0    101    Alice         IT   25   50000           2   Kathmandu
8    109      Ian         HR   28   52000           3   Nepalgunj
4    105      Eva  Marketing   27   54000           3  Biratnagar
2    103  Charlie    Finance   29   58000           4    Lalitpur
9    110     Jane  Marketing   30   61000           5    Janakpur
1    102      Bob         HR   31   62000           6     Pokhara
7    108    Helen    Finance   33   70000           8     Chitwan
3    104    David         IT   35   80000          10   Bhaktapur
5    106    Frank      Sales   40   90000          15      Butwal

In [33]:
data.sort_values(by='Salary',ascending=False)

   EmpID     Name Department  Age  Salary  Experience        City
5    106    Frank      Sales   40   90000          15      Butwal
3    104    David         IT   35   80000          10   Bhaktapur
7    108    Helen    Finance   33   70000           8     Chitwan
1    102      Bob         HR   31   62000           6     Pokhara
9    110     Jane  Marketing   30   61000           5    Janakpur
2    103  Charlie    Finance   29   58000           4    Lalitpur
4    105      Eva  Marketing   27   54000           3  Biratnagar
8    109      Ian         HR   28   52000           3   Nepalgunj
0    101    Alice         IT   25   50000           2   Kathmandu
6    107    Grace         IT   24   48000           1      Dharan

In [34]:
data.sort_values(by='Name')

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [35]:
data.sort_values(by=['Salary','Name'])

   EmpID     Name Department  Age  Salary  Experience        City
6    107    Grace         IT   24   48000           1      Dharan
0    101    Alice         IT   25   50000           2   Kathmandu
8    109      Ian         HR   28   52000           3   Nepalgunj
4    105      Eva  Marketing   27   54000           3  Biratnagar
2    103  Charlie    Finance   29   58000           4    Lalitpur
9    110     Jane  Marketing   30   61000           5    Janakpur
1    102      Bob         HR   31   62000           6     Pokhara
7    108    Helen    Finance   33   70000           8     Chitwan
3    104    David         IT   35   80000          10   Bhaktapur
5    106    Frank      Sales   40   90000          15      Butwal

In [44]:
col = data.columns.to_list()
col =sorted(col)

In [38]:
df = data.copy()
df

   EmpID     Name Department  Age  Salary  Experience        City
0    101    Alice         IT   25   50000           2   Kathmandu
1    102      Bob         HR   31   62000           6     Pokhara
2    103  Charlie    Finance   29   58000           4    Lalitpur
3    104    David         IT   35   80000          10   Bhaktapur
4    105      Eva  Marketing   27   54000           3  Biratnagar
5    106    Frank      Sales   40   90000          15      Butwal
6    107    Grace         IT   24   48000           1      Dharan
7    108    Helen    Finance   33   70000           8     Chitwan
8    109      Ian         HR   28   52000           3   Nepalgunj
9    110     Jane  Marketing   30   61000           5    Janakpur

In [48]:
df.columns=col
df

   Age     City Department  EmpID  Experience  Name      Salary
0  101    Alice         IT     25       50000     2   Kathmandu
1  102      Bob         HR     31       62000     6     Pokhara
2  103  Charlie    Finance     29       58000     4    Lalitpur
3  104    David         IT     35       80000    10   Bhaktapur
4  105      Eva  Marketing     27       54000     3  Biratnagar
5  106    Frank      Sales     40       90000    15      Butwal
6  107    Grace         IT     24       48000     1      Dharan
7  108    Helen    Finance     33       70000     8     Chitwan
8  109      Ian         HR     28       52000     3   Nepalgunj
9  110     Jane  Marketing     30       61000     5    Janakpur

In [50]:
data.sort_index(axis=1)

   Age        City Department  EmpID  Experience     Name  Salary
0   25   Kathmandu         IT    101           2    Alice   50000
1   31     Pokhara         HR    102           6      Bob   62000
2   29    Lalitpur    Finance    103           4  Charlie   58000
3   35   Bhaktapur         IT    104          10    David   80000
4   27  Biratnagar  Marketing    105           3      Eva   54000
5   40      Butwal      Sales    106          15    Frank   90000
6   24      Dharan         IT    107           1    Grace   48000
7   33     Chitwan    Finance    108           8    Helen   70000
8   28   Nepalgunj         HR    109           3      Ian   52000
9   30    Janakpur  Marketing    110           5     Jane   61000